Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.10.2"
  # config.hostname = "www3.development
end

# searcg for how to add a host, that will allow us to go to a normal link
  # development.local --> endup in the welcome to ngix website

